version: '3.8'
services:
    mysqldb:
        platform: linux/x86_64
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - .db:/var/lib/mysqldock
        environment:
            MYSQL_DATABASE: 'henry-gets-moving'
            MYSQL_USER: 'henry-gets-moving'
            MYSQL_PASSWORD: 'nxZnL&90OJ4j'
            MYSQL_ROOT_PASSWORD: 'nxZnL&90OJ4j'
            MYSQL_ROOT_HOST: '%'
            MYSQL_HOST: '%'
    backend:
        depends_on:
            - mysqldb
        ports:
            - 3333:3333
        build:
            dockerfile: ./Dockerfile
        stdin_open: true
        volumes:
            - .:/app
