name: automated unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  run-tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.5.0
      - name: setup node
        uses: actions/setup-node@v3
      - name: install dependencies
        run: npm install
      - name: run tests
        run: node ace test